services:
  # =========================
  # AUTH DATABASE
  # =========================
  postgres:
    image: postgres:16
    container_name: auth_postgres
    restart: always
    environment:
      TZ: "Asia/Bangkok"
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
     
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  # =========================
  # CONTRACT DATABASE
  # =========================
  contract_postgres:
    image: postgres:16
    container_name: contract_postgres
    restart: always
    environment:
      Z: "Asia/Bangkok"
      POSTGRES_USER: ${CONTRACT_DB_USER}
      POSTGRES_PASSWORD: ${CONTRACT_DB_PASSWORD}
      POSTGRES_DB: ${CONTRACT_DB_NAME}
  
    ports:
      - "5434:5432"
    volumes:
      - contract_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CONTRACT_DB_USER} -d ${CONTRACT_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s


  # =========================
  # AUTH SERVICE
  # =========================
  auth-service:
    build: ./auth-service
    container_name: auth_service
    env_file: .env
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      TZ: "Asia/Bangkok"


  # =========================
  # CONTRACT SERVICE
  # =========================
  contract-service:
    build: ./contract-service
    container_name: contract_service
    env_file: .env
    ports:
      - "8082:8082"
    depends_on:
      contract_postgres:
        condition: service_healthy
    restart: always
    environment:
      TZ: "Asia/Bangkok"


volumes:
  pgdata:
  contract_pgdata:
